language: php

sudo: false

php:
  - 7

install:
  - yes '' | pecl install -f mongo
  - composer self-update
  - composer install --prefer-source --no-interaction --ignore-platform-reqs

script:
  - phpunit
