language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
#  - 7

install:
  - yes '' | pecl install -f mongo
  - composer self-update
  - composer install --dev --prefer-source --no-interaction

script:
  - phpunit
