language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7

before_script:
  - pecl install -f mongo-1.2.12

install:
  - composer self-update
  - composer install --dev --prefer-source --no-interaction

script:
  - phpunit
